Repository Munich-Quantum-Software-Stack/QDMI, pull requests merged in 2024-10, with the labels that each got.

#64 📝 Change Icon in "DOCUMENTATION"-Button
  README.md
Labels: documentation, enhancement, fix

#67 ✏️ remove redundant abbreviation in readme header
  README.md
Labels: documentation

#71 ✨ Add C++ Example Device
  .clang-tidy
  examples/device/CMakeLists.txt
  examples/device/c/device.c
  examples/device/cxx/CMakeLists.txt
  examples/device/cxx/device.cpp
  include/qdmi/client/control.h
  include/qdmi/client/query.h
  include/qdmi/device/control.h
  include/qdmi/device/query.h
  test/CMakeLists.txt
  test/test_qdmi.cpp
Labels: enhancement, usability, feature

#70 👷 Set up continuous integration
  .clang-tidy
  .github/codecov.yml
  .github/release-drafter.yml
  .github/workflows/ci.yml
  .github/workflows/release-drafter.yml
  .github/workflows/reusable-change-detection.yml
  .github/workflows/reusable-cpp-ci.yml
  .github/workflows/reusable-docs.yml
  .pre-commit-config.yaml
  CMakeLists.txt
  cmake/ExternalDependencies.cmake
  examples/device/cxx/device.cpp
  test/utils/test_impl.cpp
  test/utils/test_impl.hpp
Labels: continuous integration

#72 ✨ Add Project Templates for Devices
  .github/workflows/reusable-change-detection.yml
  CMakeLists.txt
  templates/device/CMakeLists.txt
  templates/device/cmake/ExternalDependencies.cmake
  templates/device/src/CMakeLists.txt
  templates/device/src/my_device.cpp
  templates/device/test/CMakeLists.txt
  templates/device/test/test_my_device.cpp
  test/CMakeLists.txt
Labels: usability, feature

#75 🚨 Fix shadowing of global devices list in qdmi_example_driver.cpp
  examples/driver/qdmi_example_driver.cpp
Labels: code quality

#76 ⚡ enable compiler cache if available
  CMakeLists.txt
  cmake/Cache.cmake
Labels: usability

#78 🚨 Fix uncontrolled data used in path expression
  examples/driver/qdmi_example_driver.cpp
Labels: code quality

#84 ♻️ Fixing Various Bugs
  examples/device/c/CMakeLists.txt
  examples/device/cxx/CMakeLists.txt
  examples/driver/qdmi_example_driver.cpp
  examples/fomac/example_fomac.cpp
  include/qdmi/client/query.h
  include/qdmi/common/types.h
  include/qdmi/device/query.h
  templates/device/src/my_device.cpp
  test/test_qdmi.cpp
  test/utils/test_defs.cpp
Labels: bug, documentation, fix
