Repository Munich-Quantum-Software-Stack/QDMI, pull requests merged in 2024-11, with the labels that each got.

#85 🎨 Use `size_t` for buffer sizes and countable quantities in general
  examples/device/c/device.c
  examples/device/cxx/device.cpp
  examples/driver/qdmi_example_driver.cpp
  examples/fomac/example_fomac.cpp
  examples/fomac/example_fomac.hpp
  examples/tool/example_tool.cpp
  include/qdmi/client/control.h
  include/qdmi/client/query.h
  include/qdmi/common/enums.h
  include/qdmi/device/control.h
  include/qdmi/device/query.h
  include/qdmi/driver/session.h
  templates/device/src/my_device.cpp
  templates/device/test/test_my_device.cpp
  test/test_qdmi.cpp
  test/utils/test_impl.cpp
Labels: code quality

#82 ✨ Add Readout Format for State Vector and Probabilities
  docs/examples.md
  examples/device/c/device.c
  examples/device/cxx/device.cpp
  include/qdmi/common/enums.h
  test/test_qdmi.cpp
Labels: feature

#87 🐛 fix condition for deployment of docs
  .github/workflows/reusable-docs.yml
Labels: documentation, fix

#97 Fix license
  CMakeLists.txt
  README.md
  cmake/Cache.cmake
  cmake/CompilerWarnings.cmake
  cmake/ExternalDependencies.cmake
  cmake/PrefixHandling.cmake
  cmake/qdmi-config.cmake.in
  docs/CMakeLists.txt
  docs/Doxyfile.in
  docs/examples.md
  docs/faq.md
  docs/guide.md
  docs/header.html
  docs/index.md
  docs/layout.xml
  docs/rationale.md
  docs/style.css
  docs/support.md
  docs/templates.md
  examples/CMakeLists.txt
  examples/device/CMakeLists.txt
  examples/device/c/CMakeLists.txt
  examples/device/c/device.c
  examples/device/cxx/CMakeLists.txt
  examples/device/cxx/device.cpp
  examples/driver/CMakeLists.txt
  examples/driver/qdmi_example_driver.cpp
  examples/driver/qdmi_example_driver.h
  examples/fomac/CMakeLists.txt
  examples/fomac/example_fomac.cpp
  examples/fomac/example_fomac.hpp
  examples/tool/CMakeLists.txt
  examples/tool/example_tool.cpp
  examples/tool/example_tool.hpp
  include/qdmi/client.h
  include/qdmi/client/control.h
  include/qdmi/client/query.h
  include/qdmi/common/enums.h
  include/qdmi/common/types.h
  include/qdmi/device.h
  include/qdmi/device/control.h
  include/qdmi/device/query.h
  include/qdmi/device/types.h
  include/qdmi/driver.h
  include/qdmi/driver/session.h
  include/qdmi/driver/types.h
  templates/CMakeLists.txt
  templates/device/CMakeLists.txt
  templates/device/cmake/ExternalDependencies.cmake
  templates/device/src/CMakeLists.txt
  templates/device/src/my_device.cpp
  templates/device/test/CMakeLists.txt
  templates/device/test/test_my_device.cpp
  test/CMakeLists.txt
  test/test_qdmi.cpp
  test/utils/test_defs.cpp.in
  test/utils/test_impl.cpp
  test/utils/test_impl.hpp
Labels: fix, usability

#99 📝 Remove not implemented functionality from comment
  include/qdmi/driver/session.h
Labels: documentation, fix

#100 Provision to set session parameters
  examples/driver/qdmi_example_driver.cpp
  include/qdmi/common/enums.h
  include/qdmi/common/types.h
  include/qdmi/driver/session.h
  test/utils/test_impl.cpp
Labels: enhancement

#101 🧪 Test Installation of QDMI
  .github/workflows/reusable-cpp-ci.yml
  .github/workflows/reusable-cpp-install-tests.yml
  .gitignore
  CMakeLists.txt
  cmake/ExternalDependencies.cmake
Labels: fix, usability, continuous integration, code quality

#102 📝 add citation information
  CITATION.cff
  README.md
Labels: documentation

#104 🍱 update QDMI figures
  docs/_static/qdmi.svg
  docs/_static/qdmi_dark.svg
  docs/_static/qdmi_schematic.svg
  docs/_static/qdmi_schematic_dark.svg
Labels: documentation

#103 🔖 version v1
  CMakeLists.txt
  README.md
  docs/Doxyfile.in
  examples/device/c/device.c
  examples/device/cxx/device.cpp
Labels: documentation, major
