Repository Munich-Quantum-Software-Stack/QDMI, pull requests merged in 2024-12, with the labels that each got.

#120 🐛 Fix an inconsistency in the docs about coupling maps
  include/qdmi/common/enums.h
Labels: bug, documentation

#121 🩹 fix potential target conflict
  CMakeLists.txt
  examples/driver/CMakeLists.txt
  examples/fomac/CMakeLists.txt
Labels: fix

#122 🎨 Stability improvements for custom enum parameters
  examples/driver/qdmi_example_driver.cpp
  include/qdmi/client/control.h
  include/qdmi/common/enums.h
  include/qdmi/device/control.h
  include/qdmi/driver/session.h
  test/test_qdmi.cpp
  test/utils/test_impl.cpp
Labels: refactor, fix
