Repository Munich-Quantum-Software-Stack/QDMI, pull requests merged in 2025-08, with the labels that each got.

#198 ✨ Communicating the Location of Sites
  examples/device/device.cpp
  include/qdmi/constants.h
  test/CMakeLists.txt
  test/test_qdmi.cpp
Labels: enhancement

#199 ✨ Report the Scope of an Operation
  docs/rationale.md
  examples/device/device.cpp
  include/qdmi/constants.h
  test/test_qdmi.cpp
Labels: enhancement

#209 ✨ Report Minimal Atom Distance
  include/qdmi/constants.h
  test/test_qdmi.cpp
Labels: enhancement

#212 ♻️ Update PR Template, Changelog, and Upgrading Guide
  .github/pull_request_template.md
  CHANGELOG.md
  UPGRADING.md
Labels: documentation, usability

#214 🐛 Fix Install Instructions
  CHANGELOG.md
  CMakeLists.txt
Labels: fix

#219 👷🏼 Better support for PRs from forks
  .github/workflows/ci.yml
  .github/workflows/reusable-docs.yml
Labels: continuous integration

#220 💚 Replace coverage job with in-repo workflow
  .github/workflows/reusable-cpp-ci.yml
Labels: continuous integration
